services:
  - type: web
    name: no-more-booking
    plan: free
    env: docker
    dockerfilePath: Dockerfile.render
    dockerContext: .
    region: frankfurt
    branch: main
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: no-more-booking-db
          property: connectionString
      - key: MAILER_DSN
        value: smtp://bc484694b30f0a:bdc8204781ab57@sandbox.smtp.mailtrap.io:2525

databases:
  - name: no-more-booking-db
    plan: free
    databaseName: no_more_book
    user: nomorebook_user
