name: CI Symfony

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  symfony:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/no_more_book_test"

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: no_more_book_test
        ports: [3306:3306]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./noMoreBook

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" -uroot -proot --silent; do
            sleep 1
          done

      - name: Create database & run migrations
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --env=test --no-interaction
          php bin/console doctrine:fixtures:load --env=test --no-interaction
        working-directory: ./noMoreBook

      - name: Run PHPUnit tests
        run: php bin/phpunit
        working-directory: ./noMoreBook

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --level=max
        working-directory: ./noMoreBook

      - name: Lint PHP
        run: find src/ -name "*.php" | xargs -n 1 php -l
        working-directory: ./noMoreBook

      - name: Lint YAML
        run: php bin/console lint:yaml config
        working-directory: ./noMoreBook

      - name: Lint Twig
        run: php bin/console lint:twig templates
        working-directory: ./noMoreBook
